### ISSUE TITLE
Subscript selector popup doesn't update internal state

### ISSUE THREAD

**Issue by TrakJohnson** [Mapioi/unhexennium#2]
The internal state of the parentheses' subscript selector doesn't seem to update.

**Comment by Pyxidatol-C** [comment]
![ezgif-1-3cdfe70e1e](https://user-images.githubusercontent.com/13273623/39970749-2486ab04-56f1-11e8-8f9e-8d8643c6a395.gif)

**Comment by Pyxidatol-C** [comment]
https://github.com/Mapioi/unhexennium/blob/master/lib/tabs/popups.dart#L493

`widget.currentSubscript` instead of `selectedSubscript` was used.

well, (git) blame me.

Also, `onError` in `num.parse` is deprecated. I will fix that as well.
