### ISSUE TITLE
Incorrect number of elements in formula

### ISSUE THREAD

**Issue by Pyxidatol-C** [Mapioi/unhexennium#6]
![simulator screen shot - iphone x - 2018-10-09 at 21 00 23](https://user-images.githubusercontent.com/13273623/46693266-9ae0dd00-cc09-11e8-8b60-32e6ad813ec3.png)
![simulator screen shot - iphone x - 2018-10-09 at 21 00 37](https://user-images.githubusercontent.com/13273623/46693268-9ae0dd00-cc09-11e8-9c43-14491a857a01.png)
Explanation: If `RFM(C.2 H2O) = 2 * RFM(C.H2O)` -- it seems like the parser wrongly associates the coefficient  `2` for the water of crystallisation with the rest as well.

I speculate that it might not be specific to water of crystallisation.

**Comment by Pyxidatol-C** [comment]
Most likely due to this line using `> 1` instead of `>= 1` (or `.isNotEmpty`): https://github.com/Mapioi/unhexennium/blob/9d545ea9e4ed4c5a2bde94af73df3199731925bd/lib/chemistry/formula.dart#L637

**Comment by TrakJohnson** [comment]
Let's do like le capitaine for bugs
![image](https://user-images.githubusercontent.com/9513815/46738150-bb5a7700-cc9d-11e8-8ae7-c147a90b76bd.png)
